---
title: "year end run plot"
author: "Katie Masiello"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# devtools::install_github("kmasiello/runkeepR")

library(runkeepR)
library(strava)
library(tidyverse)
library(lubridate)
library(showtext)
library(ggtext)

```

# Import and prepare data from Runkeeper 
```{r Runkeeper Import}
# Directory containing gpx files exported from Runkeeper (https://runkeeper.com/exportData)
gpx_dir <- "01-runkeeper-data-export-2021-12-21-011508"

data_raw <- runkeepR::load_tracks(gpx_dir)

# save(data_raw, file="data_raw_kam.rds") ## save to avoid re-processing
# load("data_raw_kam.rds")

year <- "2021"
activity <- "Running"

data_clean <- data_raw %>% filter(Year == year & Type == activity) %>% 
  rename(dist = `Distance (mi)`) %>% 
  rename_with(tolower) %>% 
  select(trkname, date, year, month, day, time, duration, dist, latitude, longitude) %>%
  arrange(date)

```

# Import and prepare data from Strava
```{r Strava Import}
export_dir <- here::here("rj")

# Strava exported data is organized differently than Runkeeper. The exported folder structure looks something like this:
# export_70092700/
# ├── activities
# │   ├── 4221925302.gpx
# │   ├── 4230335771.gpx
# ...  ...
# │   └── 6362384981.gpx
# ├── activities.csv
# ...

# The `strava::process_data` function does not parse the activity type, so we have to cross reference activity IDs with gpx file names.

# Read in `activities.csv` file from Strava export that lists Activity Type and Activity ID
descr_raw <- readr::read_csv(here::here(export_dir, "activities.csv")) 

descr <- descr_raw %>% 
  mutate(date = mdy_hms(`Activity Date`,tz=Sys.timezone())) %>% 
  select(`Activity ID`, date, `Activity Type`)

year <- "2021"
activity <- "Run"

selected_ids <- descr %>% 
  filter(`Activity Type` == activity & year(date) == year)

selected_gpx_filenames <- selected_ids %>% pull(`Activity ID`) %>% paste0(".gpx")

# Put `activity` gpx files in separate directory.
# fs::dir_create(here::here(export_dir, "selected_activities"))
# fs::file_copy(path=here::here(export_dir, "activities",selected_gpx_filenames),
#               new_path=here::here(export_dir,"selected_activities"))

gpx_dir <- here::here(export_dir,"selected_activities")

data_raw <- process_data(gpx_dir) %>% as_tibble()
# save(data_raw, file="data_raw.rds") ## save to avoid re-processing
# load("data_raw_sml.rds")

data_clean <- data_raw %>% 
  mutate(year=year(time), month=month(time), day=day(time)) %>%
  rename(latitude=lat, longitude=lon) %>%
  group_by(id) %>%
  mutate(date = first(time)) %>%
  mutate(dist = last(cumdist))
```

#Plot
```{r}
### Some Colors
linen <- "#faf0e6"
lt_linen <- "#fbf7f0"
dark_grayblue <- "#656D79"
slate_blue <- "#6C8498"
fox_brown <- "#493D3F"
mud <- "#6B6B6B"
v_lt_blue <- "#F1F6F8"

### Color palettes for gradients
colors_blues <- c("#bbd5db", "#4b7d8d", "#1f4752")
colors_greens <- c("#d5e5d7", "#6c7904",  "#1d3110")
colors_steels <- c("#bbd5db", "lightsteelblue3",  "#141227")

col_palette <- colors_steels
caption <- "500 miles \U2022 2021"
```

```{r}

font_add_google("Monoton")
font_add("fa-solid", "~/Downloads/fontawesome-free-5.15.4-desktop/otfs/Font Awesome 5 Free-Solid-900.otf")
# ^- this is a lousy way of doing this
showtext_auto()

# plot it

ggplot((data_clean %>% filter(!is.na(latitude))),
       aes(x = longitude, y = latitude, color=dist)) +
  scale_color_gradientn(colors = col_palette) +
  labs(tag="\Uf70c",
       caption=caption) +
  geom_path(size=0.4) +
  facet_wrap( ~ as.character(date), scales = "free", ncol=12) +
  theme(
    text=element_text(),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none",
    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title=element_blank(),
    plot.subtitle=element_blank(),
    strip.text = element_blank(),
    plot.caption=element_text(family="Monoton", colour=mud, size=39),
    plot.tag.position = c(1345/4675, 180/5360), #will require manual tweaking
    plot.tag=element_text(family="fa-solid", colour=mud, size=39),
    plot.background = element_rect(colour = col_palette[3], fill=v_lt_blue, size=8),
    plot.margin = margin(t = 20,  # Top margin
                         r = 20,  # Right margin
                         b = 15,  # Bottom margin
                         l = 20,  # Left margin
                         ) 
  
  )

ratio <- 4.1/3.2 #h/w
height <- 10
ggsave(here::here("kam_long_rev12.png"), dpi = 600, width = height/ratio, height = height, units = "in")

```

